name: Pinterest Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 */3 * *' # every 3 days at 15:00 WIB

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Scrape Script
        run: node ./src/scripts/scrape-board.mjs

      - name: Setup Git for pushing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Push Changes
        run: |
          git add .
          git commit -m "chore: update Pinterest board images 🖼️"
          git push
